routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();
Route::get('/users','HomeController@users');
//Route::get('/pak', 'HomeController@getunsur');
Route::get('/pak/{id}', 'HomeController@getunsur');
Route::get('getsubunsur','HomeController@getsubunsur' );
Route::get('getsubbidang','HomeController@getsubbidang' );
Route::get('getangkakredit', 'HomeController@getangkakredit');
Route::post('getpengajuan','Pengajuan@update' );
Route::post('postpak','AngkaKreditController@postpak');
Route::get('/profile','HomeController@profile')->name('profile'); //profile si dosen -> profile.blade.php
Route::get('/table', function()
{
  return view('table');
});
Route::get('/user', function()
{
  return view('user');
});
Route::get('/input/angkakredit', 'AngkaKreditController@index')->name('angkakredit');
//Route::get('/metu', 'HomeController@logout')->name('logout');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware'=>'auth'], function () {

	Route::get('permissions-all-users',['middleware'=>'check-permission:user|admin|superadmin','uses'=>'HomeController@allUsers']);

	Route::get('permissions-admin-superadmin',['middleware'=>'check-permission:admin|superadmin','uses'=>'HomeController@adminSuperadmin']);

	Route::get('permissions-superadmin',['middleware'=>'check-permission:superadmin','uses'=>'HomeController@superadmin']);

});
Route::resource('pengajuan', 'Pengajuan');

//punya kepegawaian dan penilai
Route::resource('penilai-internal','PenilaiInternalController'); // menampilkan master penilai internal
Route::resource('riwayat','RiwayatController'); // menampilkan riwayat menilai dari penilaian
Route::resource('penilai-eksternal','PenilaiEksternalController'); // menampilkan master penilai eksternal
Route::get('/ubah-penilai/{id}','PenilaiEksternalController@edit_data' ); // menuju tampilan edit
Route::resource('pilih-penilai','PilihPenilaiController'); // memilih penilai
Route::resource('penilaian','NilaiPAKController'); // menampilkan data pengajuan yang akan dinilai
Route::get('/nilai-pak/{id}', 'NilaiPAKController@getunsur2'); // tampilan penilaian PAK
Route::get('/isi-nilai/{id}', 'NilaiPAKController@dapat_rubrik'); // dapatkan id rubrik
Route::get('tambah-penilai','PenilaiEksternalController@tambah_data'); // tampilan tambah data penilai eksternal
Route::delete('/hapus-penilai/{id}','PenilaiEksternalController@destroy'); // hapus data penilai eksternal
Route::get('dupak','HomeController@dupak');//ke view dupak

Route::post('insertpenilai/{id}','PilihPenilaiController@pilih');
Route::get('/data', 'fakultas@index');
Route::post('/data/update', 'fakultas@update');
Route::get('/suket/{id}', 'fakultas@suket');

// Route::get('/pengajuan', 'DosenController@pengajuan');
// Route::post('postpengajuan', 'DosenController@postpengajuan')->name('pengajuan');

app/Penilai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

// model penilai eksternal
class Penilai extends Model
{
    protected $table = 'penilai_eksternal';
    public $timestamps = false;
}

resources/views/penilai/isi-nilai.blade.php
@extends('layouts.template')
@section('css')
  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/bootstrap.min.css')}}">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/datatables.bootstrap.min.css')}}"/>
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/font-awesome.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/animate.min.css')}}" />
  <link href="{{asset('asset/css/style.css')}}" rel="stylesheet">
  <!-- end: Css -->

  <!-- end: Css -->
  <!-- end: Css -->

  <link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">

@endsection

@section('profile')
  <li class="user-name"><span>{{auth::user()->username}}</span></li>
                    <li class="dropdown avatar-dropdown">
                     <img src="{{asset('asset/img/avatar.jpg')}}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                     <ul class="dropdown-menu user-dropdown">
                       <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
                       <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><span class="fa fa-power-off"></span> Logout</a></li>
                          {{-- Di panggil pada event onclick --}}
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>

                        </ul>
                      </li>
@endsection
@section('leftmenu')

@endsection
@section('content')
            <!-- Tambah penilai eksternal -->
            <div id="content">
              <div class="tab-wrapper text-center">
                <div class="panel box-shadow-none text-left content-header">
                  <div class="panel-body" style="padding-bottom:0px">
                    <div class="col-md-12">
                      <h3 class="animated fadeInLeft">Halaman Input Penilaian</h3>
                      <p class="animated fadeInDown">
                         Pengajuan Kenaikan Pangkat  <span class="fa-angle-right fa"></span>  Isi Nilai
                              </p>
                    </div>

                  </div>
                  <div class="col-md-12 top-20 padding-0">
                    <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading"><h3>Tambah Nilai</h3>
                       </div>
                    <div class="panel-body">
                                       @foreach ($getrubrik as $data)
                                       <form id="form" class="" action="{{ route('penilaian.update', $data->id_rubrik) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('PUT') }}
                                        <input type="hidden" name="id" value="{{ $data->id_rubrik }}">
                                        <input type="hidden" name="id_dupak" value="{{ $data->id_dupak }}">
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Nama Unsur</label>
                                         <div class="col-sm-8"><input type="text" class="form-control" id="nama_unsur" name="nama_unsur" value="{{ $data->nama_unsur }}"disabled></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Nama Sub Unsur</label>
                                         <div class="col-sm-8"><input type="text" class="form-control" id="nama_sub_unsur" name="nama_sub_unsur" disabled value="{{ $data->nama_sub_unsur }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Nama Sub Bidang</label>
                                         <div class="col-sm-8"><input type="text" class="form-control" id="nama_sub_bidang" name="nama_sub_bidang" disabled value="{{ $data->nama_sub_bidang }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Isian Rubrik</label>
                                        <div class="col-sm-8"><input type="text" class="form-control" id="isian_rubrik" name="isian_rubrik" disabled value="{{ $data->isian_rubrik }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Tanggal Mulai</label>
                                        <div class="col-sm-8"><input type="text" class="form-control" id="tgl_mulai" name="tgl_mulai" disabled value="{{ $data->tanggal_mulai }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Tanggal Berakhir Rubrik</label>
                                        <div class="col-sm-8"><input type="text" class="form-control" id="tgl_akhir" name="tgl_akhir" disabled value="{{ $data->tanggal_berakhir }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Berkas</label>
                                        <div class="col-sm-8"><a href="https://{{ $data->berkas }}" class="col-sm-2 control-label text-left" style="padding-top: 6px; font-size: 16px;">{{ $data->berkas }}</a></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Angka Kredit Total</label>
                                        <div class="col-sm-8"><input type="text" class="form-control" id="kredit_total" name="kredit_total" disabled value="{{ $data->angka_kredit_total }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Angka Kredit Penilai</label>
                                        <div class="col-sm-8"><input type="text" class="form-control" id="kredit_penilai" name="kredit_penilai" value="{{ $data->angka_kredit_penilai }}"></div>
                                        </div>
                                          <button type="reset" class="btn btn-default" data-dismiss="modal">Batal</button>
                                          <button type="submit" class="btn btn-primary">Nilai</button>
                                        
                                    </form>
                                    @endforeach
                </div>
              </div>

              </div>
            </div>
          </div>
                        <!-- end: content -->
@endsection
@section('javascript')
<!-- start: Javascript -->
  <script src="{{ asset('asset/js/jquery.min.js') }}"></script>
  <script src="{{ asset('asset/js/jquery.ui.min.js') }}"></script>
  <script src="{{ asset('asset/js/bootstrap.min.js') }}"></script>
<!-- plugins -->
  <script src="{{ asset('asset/js/plugins/moment.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.datatables.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/datatables.bootstrap.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.nicescroll.js') }}"></script>
<!-- custom -->
  <script src="{{ asset('asset/js/main.js') }}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('#datatables-example').DataTable();
  });
</script>
<!-- end: Javascript -->
@endsection

resources/views/penilai/pilih-pak.blade.php
@extends('layouts.template')
@section('css')
  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/bootstrap.min.css')}}">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/datatables.bootstrap.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/font-awesome.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/animate.min.css')}}" />

  <link href="{{asset('asset/css/style.css')}}" rel="stylesheet">

  <link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">

@endsection

@section('profile')
  <li class="user-name"><span>{{auth::user()->username}}</span></li>
                    <li class="dropdown avatar-dropdown">
                     <img src="{{asset('asset/img/avatar.jpg')}}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                     <ul class="dropdown-menu user-dropdown">
                       <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
                       <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><span class="fa fa-power-off"></span> Logout</a></li>
                          {{-- Di panggil pada event onclick --}}
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>

                        </ul>
                      </li>
@endsection
@section('leftmenu')

@endsection
@section('content')
<!-- tampilan penilai memilih pengajuan yang akan dinilai -->
<div id="content">
<div class="tab-wrapper text-center">
  <div class="panel box-shadow-none text-left content-header">
    <div class="panel-body" style="padding-bottom:0px">
      <div class="col-md-12">
        <h3 class="animated fadeInLeft"> Form Penilaian PAK</h3>
        <p class="animated fadeInDown">
            Penilaian  <span class="fa-angle-right fa"></span>  Penilaian PAK
                </p>
      </div>



    </div>
    <div class="col-md-12 top-20 padding-0">
                <div class="col-md-12">
                  <div class="panel">
                    <div class="panel-heading"><h3>Penilaian PAK </h3>

                    </div>
                    <div class="panel-body">
                      <div class="responsive-table">
                      <!-- tabel pengajuan -->
                      <table id="datatables-example" class="table table-striped table-bordered" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th hidden></th>
                          <th style="width:4%; text-align: center;">No</th>
                          <th style="width:30%; text-align: center;">Nama</th>
                          <th style="width:15%; text-align: center;">Jabatan Asal</th>
                          <th style="width:15%; text-align: center;">Jabatan Tujuan</th>
                          <th style="width:13%; text-align: center;">Link</th>
                          <th style="width:13%; text-align: center;">Status</th>
                          <th style="width:10%; text-align: center;">Aksi</th>
                        </tr>
                      </thead>
                      <tbody>
                       @php $no = 1; @endphp 
                          @foreach ( $penilaian as $data)
                          <tr>
                            <td hidden>{{$data->id}}</td>
                            <td style="text-align: center;">{{ $no++ }}</td>
                            <td>{{ $data->nama }}</td>
                            <td>{{ $data->jabatan_asal }}</td>
                            <td>{{ $data->jabatan_tujuan }}</td>
                            <td><a href="https://{{ $data->link_drive }}">Link</a></td>
                            <td>
                                @if ($data->status == 'Sedang Dinilai')
                                <span class="btn btn-flat btn-primary" style="width:130px; height:28px; pointer-events: none; border: 0px;">Sedang Dinilai</span>
                                @else
                                <span class="btn btn-flat btn-default" style="width:130px; height:28px; pointer-events: none; border: 0px;">Menunggu Dinilai</span>
                                @endif
                            </td>
                            <td>
                              <a class="btn btn-circle btn-mn btn-primary" href="{{ url('/nilai-pak/'.$data->id) }}"> <span class="fa fa-pencil" style="padding-top: 7px;"></span> </a>
                               <button type="button" class="btn btn-circle btn-mn btn-success"><span class="fa fa-check" ></span></button>
                            </td>
                            </tr>
                          @endforeach
                         </tbody>
                        </table>
                      </div>
                  </div>
                  <!-- Modal -->
                </div>
              </div>
              </div>
            </div>
  </div>
</div>
</div>
@endsection
@section('javascript')
  <script src="{{ asset('asset/js/jquery.min.js') }}"></script>
  <script src="{{ asset('asset/js/jquery.ui.min.js') }}"></script>
  <script src="{{ asset('asset/js/bootstrap.min.js') }}"></script>
<!-- plugins -->
  <script src="{{ asset('asset/js/plugins/moment.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.datatables.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/datatables.bootstrap.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.nicescroll.js') }}"></script>
  <script type="text/javascript">
  $(document).ready(function(){
    $('#datatables-example').DataTable();
  });
</script>
<!-- custom -->
<script src="{{ asset('asset/js/main.js') }}"></script>

@endsection

resources/views/penilai/riwayat.blade.php
@extends('layouts.template')
@section('css')
  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/bootstrap.min.css')}}">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/datatables.bootstrap.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/font-awesome.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/animate.min.css')}}" />

  <link href="{{asset('asset/css/style.css')}}" rel="stylesheet">

  <link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">

@endsection

@section('profile')
  <li class="user-name"><span>{{auth::user()->username}}</span></li>
                    <li class="dropdown avatar-dropdown">
                     <img src="{{asset('asset/img/avatar.jpg')}}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                     <ul class="dropdown-menu user-dropdown">
                       <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
                       <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><span class="fa fa-power-off"></span> Logout</a></li>
                          {{-- Di panggil pada event onclick --}}
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>

                        </ul>
                      </li>
@endsection
@section('leftmenu')

@endsection
@section('content')
<!-- tampilan pilih penilai -->
<div id="content">
<div class="tab-wrapper text-center">
  <div class="panel box-shadow-none text-left content-header">
    <div class="panel-body" style="padding-bottom:0px">
      <div class="col-md-12">
        <h3 class="animated fadeInLeft"> Penilaian</h3>
        <p class="animated fadeInDown">
            Penilaian  <span class="fa-angle-right fa"></span>  Riwayat Penilaian
                </p>
      </div>



    </div>
    <div class="col-md-12 top-20 padding-0">
                <div class="col-md-12">
                  <div class="panel">
                    <div class="panel-heading"><h3>Penilaian PAK </h3>
                
                    </div>
                    <div class="panel-body">
                      <div class="responsive-table">
                        <!-- tabel pengajuan yang selesai -->
                      <table id="datatables-example" class="table table-striped table-bordered" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th style="width:4%; text-align: center;">No</th>
                          <th style="width:30%; text-align: center;">Nama</th>
                          <th style="width:15%; text-align: center;">Jabatan Asal</th>
                          <th style="width:15%; text-align: center;">Jabatan Tujuan</th>
                          <th style="width:13%; text-align: center;">Link</th>
                          <th style="width:13%; text-align: center;">Status</th>
                          <th style="width:7%; text-align: center;">Aksi</th>
                        </tr>
                      </thead>
                      <tbody>
                        @php $no = 1; @endphp
                          @foreach ( $penilaian as $data)
                          <tr>
                            <td hidden>{{$data->id}}</td>
                            <td style="text-align: center;">{{ $no++ }}</td>
                            <td>{{ $data->nama }}</td>
                            <td>{{ $data->jabatan_asal }}</td>
                            <td>{{ $data->jabatan_tujuan }}</td>
                            <td><a href="https://{{ $data->link_drive }}">{{$data->link_drive}}</a></td>
                            <td>
                                <span class="btn btn-flat btn-success" style="width:130px; height:28px; pointer-events: none; border: 0px;">Selesai</span>
                            </td>
                            <td> 
                              <a class="btn btn-circle btn-mn btn-primary" href="{{ url('/nilai-pak/'.$data->id) }}"> <span class="fa fa-eye" style="padding-top: 7px;"></span> </a> 
                            </td>
                            </tr>
                          @endforeach

                         </tbody>
                        </table>
                      </div>

                  </div>
                  <!-- Modal -->


                </div>


              </div>

              </div>
            </div>


  </div>


</div>
</div>
@endsection
@section('javascript')
  <script src="{{ asset('asset/js/jquery.min.js') }}"></script>
  <script src="{{ asset('asset/js/jquery.ui.min.js') }}"></script>
  <script src="{{ asset('asset/js/bootstrap.min.js') }}"></script>
<!-- plugins -->
  <script src="{{ asset('asset/js/plugins/moment.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.datatables.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/datatables.bootstrap.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.nicescroll.js') }}"></script>
<!-- custom -->
  <script src="{{ asset('asset/js/main.js') }}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('#datatables-example').DataTable();
  });
</script>
@endsection

resources/views/penilai/unggah-sk.blade.php
@extends('layouts.template')
@section('css')
  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/bootstrap.min.css')}}">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/datatables.bootstrap.min.css')}}"/>
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/font-awesome.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/animate.min.css')}}" />

  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/select2.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/dropzone.css')}}" />

  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/bootstrap-material-datetimepicker.css')}}" />

  <link href="{{asset('asset/css/style.css')}}" rel="stylesheet">
  <!-- end: Css -->

  <!-- end: Css -->
  <link rel="stylesheet" href="{{asset('asset/date/css/datepicker.css')}}">
  <link rel="stylesheet" href="{{asset('asset/date/css/main.css')}}">
  <!-- end: Css -->

  <link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">

@endsection

@section('profile')
  <li class="user-name"><span>{{auth::user()->username}}</span></li>
                    <li class="dropdown avatar-dropdown">
                     <img src="{{asset('asset/img/avatar.jpg')}}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                     <ul class="dropdown-menu user-dropdown">
                       <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
                       <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><span class="fa fa-power-off"></span> Logout</a></li>
                          {{-- Di panggil pada event onclick --}}
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>

                        </ul>
                      </li>
@endsection
@section('leftmenu')

@endsection

@section('content')

      <!-- unggah sk -->
        <div id="content">
          <div class="panel box-shadow-none content-header">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3 class="animated fadeInLeft">Unggah SK</h3>
                    <p class="animated fadeInDown">
                      Unggah <span class="fa-angle-right fa"></span> SK
                    </p>
                </div>
              </div>
          </div>

          <div class="col-md-12 top-20 padding-0">
                <div class="col-md-12">
                  <div class="panel">
                    <div class="panel-heading"><h3>Unggah SK Pengajuan </h3>
                    </div>
                    <div class="panel-body">
                    <form action="/file-upload" class="dropzone" id="my-awesome-dropzone"></form>
                  </div>
                </div>
              </div>
            </div>
@endsection
          
@section('javascript')
<!-- start: Javascript -->
  <script src="{{asset('asset/js/jquery.min.js')}}"></script>
  <script src="{{asset('asset/js/jquery.ui.min.js')}}"></script>
  <script src="{{asset('asset/js/bootstrap.min.js')}}"></script>


<!-- plugins -->
 <script src="{{asset('asset/js/plugins/moment.min.js')}}"></script>
 <script src="{{asset('asset/js/plugins/dropzone.js')}}"></script>
 <script src="{{asset('asset/js/plugins/jquery.nicescroll.js')}}"></script>

<!-- custom -->
<script src="{{asset('asset/js/main.js')}}"></script>
<script type="text/javascript">
  $(document).ready(function(){

  });
</script>
<!-- end: Javascript -->
@endsection