routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();
Route::get('/users','HomeController@users');
//Route::get('/pak', 'HomeController@getunsur');
Route::get('/pak/{id}', 'HomeController@getunsur');
Route::get('getsubunsur','HomeController@getsubunsur' );
Route::get('getsubbidang','HomeController@getsubbidang' );
Route::get('getangkakredit', 'HomeController@getangkakredit');
Route::post('getpengajuan','Pengajuan@update' );
Route::post('postpak','AngkaKreditController@postpak');
Route::get('/profile','HomeController@profile')->name('profile'); //profile si dosen -> profile.blade.php
Route::get('/table', function()
{
  return view('table');
});
Route::get('/user', function()
{
  return view('user');
});
Route::get('/input/angkakredit', 'AngkaKreditController@index')->name('angkakredit');
//Route::get('/metu', 'HomeController@logout')->name('logout');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware'=>'auth'], function () {

	Route::get('permissions-all-users',['middleware'=>'check-permission:user|admin|superadmin','uses'=>'HomeController@allUsers']);

	Route::get('permissions-admin-superadmin',['middleware'=>'check-permission:admin|superadmin','uses'=>'HomeController@adminSuperadmin']);

	Route::get('permissions-superadmin',['middleware'=>'check-permission:superadmin','uses'=>'HomeController@superadmin']);

});
Route::resource('pengajuan', 'Pengajuan');

//punya kepegawaian dan penilai
Route::resource('penilai-internal','PenilaiInternalController'); // menampilkan master penilai internal
Route::resource('riwayat','RiwayatController'); // menampilkan riwayat menilai dari penilaian
Route::resource('penilai-eksternal','PenilaiEksternalController'); // menampilkan master penilai eksternal
Route::get('/ubah-penilai/{id}','PenilaiEksternalController@edit_data' ); // menuju tampilan edit
Route::resource('pilih-penilai','PilihPenilaiController'); // memilih penilai
Route::resource('penilaian','NilaiPAKController'); // menampilkan data pengajuan yang akan dinilai
Route::get('/nilai-pak/{id}', 'NilaiPAKController@getunsur2'); // tampilan penilaian PAK
Route::get('/isi-nilai/{id}', 'NilaiPAKController@dapat_rubrik'); // dapatkan id rubrik
Route::get('tambah-penilai','PenilaiEksternalController@tambah_data'); // tampilan tambah data penilai eksternal
Route::delete('/hapus-penilai/{id}','PenilaiEksternalController@destroy'); // hapus data penilai eksternal
Route::get('dupak','HomeController@dupak');//ke view dupak

Route::post('insertpenilai/{id}','PilihPenilaiController@pilih');
Route::get('/data', 'fakultas@index');
Route::post('/data/update', 'fakultas@update');
Route::get('/suket/{id}', 'fakultas@suket');

// Route::get('/pengajuan', 'DosenController@pengajuan');
// Route::post('postpengajuan', 'DosenController@postpengajuan')->name('pengajuan');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/layout2.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="description" content="Miminium Admin Template v.1">
    <meta name="author" content="Isna Nur Azis">
    <meta name="keyword" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistem Informasi Kenaikan Pangkat</title>

    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="asset/css/bootstrap.min.css">

    <!-- plugins -->
    <link rel="stylesheet" type="text/css" href="asset/css/plugins/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="asset/css/plugins/simple-line-icons.css"/>
    <link rel="stylesheet" type="text/css" href="asset/css/plugins/animate.min.css"/>
    <link rel="stylesheet" type="text/css" href="asset/css/plugins/fullcalendar.min.css"/>
    <link href="asset/css/style.css" rel="stylesheet">
    <!-- end: Css -->

    <link rel="shortcut icon" href="asset/img/logomi.png">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body id="mimin" class="dashboard">
  <!-- start: Header -->
  <nav class="navbar navbar-default header navbar-fixed-top">
      <div class="col-md-12 nav-wrapper">
        <div class="navbar-header" style="width:100%;">
          <div class="opener-left-menu is-open">
            <span class="top"></span>
            <span class="middle"></span>
            <span class="bottom"></span>
        </div>
        <a href="fakultas" class="navbar-brand">
           <b>SIKP</b>
       </a>

       <ul class="nav navbar-nav search-nav">
        <li>
         <div class="search">
            <span class="fa fa-search icon-search" style="font-size:23px;"></span>
            <div class="form-group form-animate-text">
              <input type="text" class="form-text" required>
              <span class="bar"></span>
              <label class="label-search">Type anywhere to <b>Search</b> </label>
          </div>
      </div>
  </li>
</ul>

<ul class="nav navbar-nav navbar-right user-nav">
    <li class="user-name"><span>{{auth::user()->username}}</span></li>
    <li class="dropdown avatar-dropdown">
     <img src="asset/img/avatar.jpg" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
     <ul class="dropdown-menu user-dropdown">
       <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
       <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><span class="fa fa-power-off"></span> Logout</a></li>
        {{-- Di panggil pada event onclick --}}
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
   </ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
</nav>
<!-- end: Header -->

<div class="container-fluid mimin-wrapper">

  <!-- start:Left Menu -->
  <div id="left-menu">
    <div class="sub-left-menu scroll" tabindex="5000" style="overflow: hidden; outline: none;">
        <ul class="nav nav-list">
            <li><div class="left-bg"></div></li>
            <li class="time">
                <h1 class="animated fadeInLeft">21:26</h1>
                <p class="animated fadeInRight">Tuesday, November 13th 2018</p>
            </li>
            <li class="">
                <a class="tree-toggle nav-header"><span class="icons icon-docs"></span> Data Pemberkasan
                    <span class="fa-angle-right fa right-arrow text-right"></span>
                </a>
                <ul class="nav nav-list tree" style="display: none;">
                    <li><a href="data">Data Pemberkasan</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- end: Left Menu -->


<!-- start: content -->
<div id="content">
    <div class="col-md-12" style="top:20px">
        @yield('content')
        
    </div>
</div>
<!-- end: content -->

</div>

<!-- start: Mobile -->

<!-- end: Mobile -->

<!-- start: Javascript -->
<script src="asset/js/jquery.min.js"></script>
<script src="asset/js/jquery.ui.min.js"></script>
<script src="asset/js/bootstrap.min.js"></script>


<!-- plugins -->
<script src="asset/js/plugins/moment.min.js"></script>
<script src="asset/js/plugins/fullcalendar.min.js"></script>
<script src="asset/js/plugins/jquery.nicescroll.js"></script>
<script src="asset/js/plugins/jquery.vmap.min.js"></script>
<script src="asset/js/plugins/maps/jquery.vmap.world.js"></script>
<script src="asset/js/plugins/jquery.vmap.sampledata.js"></script>
<script src="asset/js/plugins/chart.min.js"></script>


<!-- custom -->
<script src="asset/js/main.js"></script>
<script type="text/javascript">
  (function(jQuery){

        // start: Chart =============

        Chart.defaults.global.pointHitDetectionRadius = 1;
        Chart.defaults.global.customTooltips = function(tooltip) {

            var tooltipEl = $('#chartjs-tooltip');

            if (!tooltip) {
                tooltipEl.css({
                    opacity: 0
                });
                return;
            }

            tooltipEl.removeClass('above below');
            tooltipEl.addClass(tooltip.yAlign);

            var innerHtml = '';
            if (undefined !== tooltip.labels && tooltip.labels.length) {
                for (var i = tooltip.labels.length - 1; i >= 0; i--) {
                    innerHtml += [
                    '<div class="chartjs-tooltip-section">',
                    '   <span class="chartjs-tooltip-key" style="background-color:' + tooltip.legendColors[i].fill + '"></span>',
                    '   <span class="chartjs-tooltip-value">' + tooltip.labels[i] + '</span>',
                    '</div>'
                    ].join('');
                }
                tooltipEl.html(innerHtml);
            }

            tooltipEl.css({
                opacity: 1,
                left: tooltip.chart.canvas.offsetLeft + tooltip.x + 'px',
                top: tooltip.chart.canvas.offsetTop + tooltip.y + 'px',
                fontFamily: tooltip.fontFamily,
                fontSize: tooltip.fontSize,
                fontStyle: tooltip.fontStyle
            });
        };
        var randomScalingFactor = function() {
            return Math.round(Math.random() * 100);
        };
        var lineChartData = {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [{
                label: "My First dataset",
                fillColor: "rgba(21,186,103,0.4)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(66,69,67,0.3)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: [18,9,5,7,4.5,4,5,4.5,6,5.6,7.5]
            }, {
                label: "My Second dataset",
                fillColor: "rgba(21,113,186,0.5)",
                strokeColor: "rgba(151,187,205,1)",
                pointColor: "rgba(151,187,205,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(151,187,205,1)",
                data: [4,7,5,7,4.5,4,5,4.5,6,5.6,7.5]
            }]
        };

        var doughnutData = [
        {
            value: 300,
            color:"#129352",
            highlight: "#15BA67",
            label: "Alfa"
        },
        {
            value: 50,
            color: "#1AD576",
            highlight: "#15BA67",
            label: "Beta"
        },
        {
            value: 100,
            color: "#FDB45C",
            highlight: "#15BA67",
            label: "Gamma"
        },
        {
            value: 40,
            color: "#0F5E36",
            highlight: "#15BA67",
            label: "Peta"
        },
        {
            value: 120,
            color: "#15A65D",
            highlight: "#15BA67",
            label: "X"
        }

        ];


        var doughnutData2 = [
        {
            value: 100,
            color:"#129352",
            highlight: "#15BA67",
            label: "Alfa"
        },
        {
            value: 250,
            color: "#FF6656",
            highlight: "#FF6656",
            label: "Beta"
        },
        {
            value: 100,
            color: "#FDB45C",
            highlight: "#15BA67",
            label: "Gamma"
        },
        {
            value: 40,
            color: "#FD786A",
            highlight: "#15BA67",
            label: "Peta"
        },
        {
            value: 120,
            color: "#15A65D",
            highlight: "#15BA67",
            label: "X"
        }

        ];

        var barChartData = {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [
            {
                label: "My First dataset",
                fillColor: "rgba(21,186,103,0.4)",
                strokeColor: "rgba(220,220,220,0.8)",
                highlightFill: "rgba(21,186,103,0.2)",
                highlightStroke: "rgba(21,186,103,0.2)",
                data: [65, 59, 80, 81, 56, 55, 40]
            },
            {
                label: "My Second dataset",
                fillColor: "rgba(21,113,186,0.5)",
                strokeColor: "rgba(151,187,205,0.8)",
                highlightFill: "rgba(21,113,186,0.2)",
                highlightStroke: "rgba(21,113,186,0.2)",
                data: [28, 48, 40, 19, 86, 27, 90]
            }
            ]
        };

        window.onload = function(){
            var ctx = $(".doughnut-chart")[0].getContext("2d");
            window.myDoughnut = new Chart(ctx).Doughnut(doughnutData, {
                responsive : true,
                showTooltips: true
            });

            var ctx2 = $(".line-chart")[0].getContext("2d");
            window.myLine = new Chart(ctx2).Line(lineChartData, {
               responsive: true,
               showTooltips: true,
               multiTooltipTemplate: "<%= value %>",
               maintainAspectRatio: false
           });

            var ctx3 = $(".bar-chart")[0].getContext("2d");
            window.myLine = new Chart(ctx3).Bar(barChartData, {
               responsive: true,
               showTooltips: true
           });

            var ctx4 = $(".doughnut-chart2")[0].getContext("2d");
            window.myDoughnut2 = new Chart(ctx4).Doughnut(doughnutData2, {
                responsive : true,
                showTooltips: true
            });

        };

        //  end:  Chart =============

        // start: Calendar =========
        $('.dashboard .calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            defaultDate: '2015-02-12',
            businessHours: true, // display business hours
            editable: true,
            events: [
            {
                title: 'Business Lunch',
                start: '2015-02-03T13:00:00',
                constraint: 'businessHours'
            },
            {
                title: 'Meeting',
                start: '2015-02-13T11:00:00',
                    constraint: 'availableForMeeting', // defined below
                    color: '#20C572'
                },
                {
                    title: 'Conference',
                    start: '2015-02-18',
                    end: '2015-02-20'
                },
                {
                    title: 'Party',
                    start: '2015-02-29T20:00:00'
                },

                // areas where "Meeting" must be dropped
                {
                    id: 'availableForMeeting',
                    start: '2015-02-11T10:00:00',
                    end: '2015-02-11T16:00:00',
                    rendering: 'background'
                },
                {
                    id: 'availableForMeeting',
                    start: '2015-02-13T10:00:00',
                    end: '2015-02-13T16:00:00',
                    rendering: 'background'
                },

                // red areas where no events can be dropped
                {
                    start: '2015-02-24',
                    end: '2015-02-28',
                    overlap: false,
                    rendering: 'background',
                    color: '#FF6656'
                },
                {
                    start: '2015-02-06',
                    end: '2015-02-08',
                    overlap: true,
                    rendering: 'background',
                    color: '#FF6656'
                }
                ]
            });
        // end : Calendar==========

        // start: Maps============

        jQuery('.maps').vectorMap({
            map: 'world_en',
            backgroundColor: null,
            color: '#fff',
            hoverOpacity: 0.7,
            selectedColor: '#666666',
            enableZoom: true,
            showTooltip: true,
            values: sample_data,
            scaleColors: ['#C8EEFF', '#006491'],
            normalizeFunction: 'polynomial'
        });

        // end: Maps==============

    })(jQuery);
</script>
<!-- end: Javascript -->
</body>
</html>

resources/views/layouts/template.blade.php
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  <meta name="description" content="Miminium Admin Template v.1">
	<meta name="author" content="Isna Nur Azis">
	<meta name="keyword" content="">
  <meta name="_token" content="{!! csrf_token() !!}"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistem Informasi Kenaikan Pangkat</title>
    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="{{asset('asset/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/simple-line-icons.css')}}"/>
    <!-- plugins -->
    <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/font-awesome.min.css')}}" />
    <link href="{{asset('asset/css/style.css')}}" rel="stylesheet">
@yield('css')

<link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">

  </head>
  <body id="mimin" class="dashboard">
    <!-- start: Header -->
      <nav class="navbar navbar-default header navbar-fixed-top">
        <div class="col-md-12 nav-wrapper">
          <div class="navbar-header" style="width:100%;">
            <div class="opener-left-menu is-open">
              <span class="top"></span>
              <span class="middle"></span>
              <span class="bottom"></span>
            </div>
              @yield('brand')
              <a href="{{ url('/') }}" class="navbar-brand">
               <b>SIKP</b>
              </a>


            <ul class="nav navbar-nav navbar-right user-nav" style="margin-right:1px">
              @yield('profile')

            </ul>
          </div>
        </div>
      </nav>
    <!-- end: Header -->

    <div class="container-fluid mimin-wrapper">

        <!-- start:Left Menu -->
          <div id="left-menu">
            <div class="sub-left-menu scroll">
              <ul class="nav nav-list">
                  <li><div class="left-bg"></div></li>
                  <li class="time">
                    <h1 class="animated fadeInLeft">21:00</h1>
                    <p class="animated fadeInRight">Sat,October 1st 2029</p>
                  </li>
                  @if (checkPermission(['superadmin']))
                    <li id="user" class="active ripple">
                      <a href="{{ url('admin/home') }}">
                         <span class="icon icon-people"></span>Kelola User
                      </a>
                    </li>
                  @endif
                  @if (checkPermission(['admin']))
                    <li id="user" class="active ripple">
                      <a href="{{ url('/users') }}">
                         <span class="icon icon-people"></span>Kelola User
                      </a>
                    </li>
                  @endif
                  <!-- menu pengajuan PAK -->
                @if (checkPermission(['user','admin','superadmin']))
                  <li class="">
                    <a class="tree-toggle nav-header"><span class="icons icon-docs"></span> Laporan
                      <span class="fa-angle-right fa right-arrow text-right"></span>
                    </a>
                    <ul class="nav nav-list tree">
                      <li><a href="{{url('dupak')}}">Dupak</a></li>
                      <li><a href="#">PAK</a></li>
                    </ul>
                  </li>
                  <li class="">
                    <a class="tree-toggle nav-header"><span class="fa fa-pencil"></span> Input
                      <span class="fa-angle-right fa right-arrow text-right"></span>
                    </a>
                    <ul class="nav nav-list tree">
                      <li><a href="{{ route('pengajuan.index') }}">Form Pengajuan</a></li>
                      {{-- <li><a href="{{ url('/pak') }}">Input PAK</a></li> --}}
                      <li><a href="{{ route('angkakredit') }}">Angka Kredit</a></li>

                    </ul>
                  </li>
                  @endif
                  <!-- menu penilai -->
                @if (checkPermission(['user','eksternal']))
                    <li class="">
                      <a class="tree-toggle nav-header">
                        <span class="fa fa-pencil-square"></span>Penilaian
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                        <ul class="nav nav-list tree">
                          <li><a href="{{ route('penilaian.index') }}">Penilaian PAK</a></li>
                          <li><a href="{{ route('riwayat.index') }}">Riwayat Penilaian</a></li>
                        </ul>
                      </li>
                  @endif
                  <!-- menu kepegawaian -->
                  @if (checkPermission(['kepegawaian']))
                    <li class="">
                        <a href="{{ route('pilih-penilai.index') }}">
                          <span class="fa fa-pencil-square"></span>Pengajuan Kenaikan Pangkat</a>
                      </li>
                    <li class="">
                      <a class="tree-toggle nav-header">
                        <span class="fa fa-user"></span>Penilai
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                        <ul class="nav nav-list tree">
                          <li><a href="{{ route('penilai-internal.index') }}">Internal</a></li>
                          <li><a href="{{ route('penilai-eksternal.index') }}">Eksternal</a></li>
                        </ul>
                      </li>
                  @endif
                  {{-- Menu Pemberkasan --}}
                  @if (checkPermission(['superadmin']))
                    <li class="">
                        <a class="tree-toggle nav-header"><span class="icons icon-docs"></span> Data Pemberkasan
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree" style="display: none;">
                            <li><a href="{{url('/data')}}">Data Pemberkasan</a></li>
                        </ul>
                    </li>
                  @endif
                @yield('leftmenu')

                </ul>
              </div>
          </div>
        <!-- end: Left Menu -->


        <!-- start: content -->
          @yield('content')
        <!-- end: content -->




    </div>
    <script src="{{asset('asset/js/jquery.min.js')}}"></script>
    <script src="{{asset('asset/js/jquery.ui.min.js')}}"></script>
    <script src="{{asset('asset/js/bootstrap.min.js')}}"></script>
  <script src="{{asset('asset/js/main.js')}}"></script>
  @yield('javascript')
  </body>
</html>