routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();
Route::get('/users','HomeController@users');
//Route::get('/pak', 'HomeController@getunsur');
Route::get('/pak/{id}', 'HomeController@getunsur');
Route::get('getsubunsur','HomeController@getsubunsur' );
Route::get('getsubbidang','HomeController@getsubbidang' );
Route::get('getangkakredit', 'HomeController@getangkakredit');
Route::post('getpengajuan','Pengajuan@update' );
Route::post('postpak','AngkaKreditController@postpak');
Route::get('/profile','HomeController@profile')->name('profile'); //profile si dosen -> profile.blade.php
Route::get('/table', function()
{
  return view('table');
});
Route::get('/user', function()
{
  return view('user');
});
Route::get('/input/angkakredit', 'AngkaKreditController@index')->name('angkakredit');
//Route::get('/metu', 'HomeController@logout')->name('logout');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware'=>'auth'], function () {

	Route::get('permissions-all-users',['middleware'=>'check-permission:user|admin|superadmin','uses'=>'HomeController@allUsers']);

	Route::get('permissions-admin-superadmin',['middleware'=>'check-permission:admin|superadmin','uses'=>'HomeController@adminSuperadmin']);

	Route::get('permissions-superadmin',['middleware'=>'check-permission:superadmin','uses'=>'HomeController@superadmin']);

});
Route::resource('pengajuan', 'Pengajuan');

//punya kepegawaian dan penilai
Route::resource('penilai-internal','PenilaiInternalController'); // menampilkan master penilai internal
Route::resource('riwayat','RiwayatController'); // menampilkan riwayat menilai dari penilaian
Route::resource('penilai-eksternal','PenilaiEksternalController'); // menampilkan master penilai eksternal
Route::get('/ubah-penilai/{id}','PenilaiEksternalController@edit_data' ); // menuju tampilan edit
Route::resource('pilih-penilai','PilihPenilaiController'); // memilih penilai
Route::resource('penilaian','NilaiPAKController'); // menampilkan data pengajuan yang akan dinilai
Route::get('/nilai-pak/{id}', 'NilaiPAKController@getunsur2'); // tampilan penilaian PAK
Route::get('/isi-nilai/{id}', 'NilaiPAKController@dapat_rubrik'); // dapatkan id rubrik
Route::get('tambah-penilai','PenilaiEksternalController@tambah_data'); // tampilan tambah data penilai eksternal
Route::delete('/hapus-penilai/{id}','PenilaiEksternalController@destroy'); // hapus data penilai eksternal
Route::get('dupak','HomeController@dupak');//ke view dupak

Route::post('insertpenilai/{id}','PilihPenilaiController@pilih');
Route::get('/data', 'fakultas@index');
Route::post('/data/update', 'fakultas@update');
Route::get('/suket/{id}', 'fakultas@suket');

// Route::get('/pengajuan', 'DosenController@pengajuan');
// Route::post('postpengajuan', 'DosenController@postpengajuan')->name('pengajuan');

resources/views/kepegawaian/edit-penilai.blade.php
@extends('layouts.template')
@section('css')
  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/bootstrap.min.css')}}">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/datatables.bootstrap.min.css')}}"/>
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/font-awesome.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/animate.min.css')}}" />
  <link href="{{asset('asset/css/style.css')}}" rel="stylesheet">
  <!-- end: Css -->

  <!-- end: Css -->
  <!-- end: Css -->

  <link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">

@endsection

@section('profile')
  <li class="user-name"><span>{{auth::user()->username}}</span></li>
                    <li class="dropdown avatar-dropdown">
                     <img src="{{asset('asset/img/avatar.jpg')}}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                     <ul class="dropdown-menu user-dropdown">
                       <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
                       <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><span class="fa fa-power-off"></span> Logout</a></li>
                          {{-- Di panggil pada event onclick --}}
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>

                        </ul>
                      </li>
@endsection
@section('leftmenu')

@endsection
@section('content')
            <!-- edit penilai eksternal -->
            <div id="content">
              <div class="tab-wrapper text-center">
                <div class="panel box-shadow-none text-left content-header">
                  <div class="panel-body" style="padding-bottom:0px">
                    <div class="col-md-12">
                      <h3 class="animated fadeInLeft"> Data Penilai Eksternal</h3>
                      <p class="animated fadeInDown">
                          Penilai  <span class="fa-angle-right fa"></span>  Edit Penilai Eksternal
                              </p>
                    </div>

                  </div>
                  <div class="col-md-12 top-20 padding-0">
                    <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading"><h3>Edit Penilai Eksternal </h3>
                       </div>
                    <div class="panel-body">
                                      @foreach ( $eksternal as $data)
                                      <form id="form" class="" action="{{ route('penilai-eksternal.update', $data->id_penilai_eks) }}" method="post">
                                        <input type="hidden" name="id" value="{{ $data->id_penilai_eks }}">
                                        {{ csrf_field() }}
                                        {{ method_field('PUT') }}
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 15px;">Nama</label>
                                         <div class="col-sm-8"><input type="text" class="form-control nama" id="nama" name="nama" value="{{ $data->nama }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 15px;">NIP</label>
                                         <div class="col-sm-8"><input type="text" class="form-control nip" id="nip" name="nip" value="{{ $data->nip }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 15px;">NIDN</label>
                                         <div class="col-sm-8"><input type="text" class="form-control nidn" id="nidn" name="nidn" value="{{ $data->nidn }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 15px;">Password</label>
                                         <div class="col-sm-8"><input type="password" class="form-control password" id="password" name="password" value="{{ $data->password }}"></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 15px;">Universitas</label>
                                          <div class="col-sm-8">
                                            <select class="form-control universitas" id="universitas" name="universitas">
                                              @foreach($universitas as $univ)
                                                @if ($univ->nama_univ == $data->universitas)
                                                <option {{ $univ->nama_univ == $data->universitas ? 'selected':'' }}> {{$data->universitas}} </option>
                                                @else
                                                <option value="{{ $univ->nama_univ }}">{{ $univ->nama_univ}}</option>
                                                @endif
                                              @endforeach
                                            </select>
                                          </div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px">
                                          <label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 15px;">Rumpun</label>
                                          <div class="col-sm-8">
                                            <select class="form-control rumpun" id="rumpun" name="rumpun">
                                              @foreach($rumpun as $rump)
                                                @if ($rump->nama_rumpun == $data->rumpun)
                                                <option {{ $rump->nama_rumpun == $data->rumpun ? 'selected':'' }}> {{$data->rumpun}} </option>
                                                @else
                                                <option value="{{ $rump->nama_rumpun }}">{{ $rump->nama_rumpun}}</option>
                                                @endif
                                              @endforeach
                                            </select>
                                          </div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 15px;">Sub Rumpun</label>
                                         <div class="col-sm-8">
                                            <select class="form-control sub_rumpun" id="sub_rumpun" name="sub_rumpun">
                                              @foreach($sub_rumpun as $srump)
                                                @if ($srump->nama_rumpun_sub == $data->sub_rumpun)
                                                <option {{ $srump->nama_rumpun_sub == $data->sub_rumpun ? 'selected':'' }}> {{$data->sub_rumpun}} </option>
                                                @else
                                                <option value="{{ $srump->nama_rumpun_sub }}">{{ $srump->nama_rumpun_sub}}</option>
                                                @endif
                                              @endforeach
                                            </select>
                                          </div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 15px;">Jabatan Fungsional</label>
                                          <div class="col-sm-8">
                                            <select class="form-control jabatan" id="jabatan" name="jabatan">
                                               @foreach($jabatan as $jab)
                                                  @if ($jab->nama_jafung == $data->jabatan)
                                                  <option {{ $jab->nama_jafung == $data->jabatan ? 'selected':'' }}> {{$data->jabatan}} </option>
                                                  @else
                                                  <option value="{{ $jab->nama_jafung }}">{{ $jab->nama_jafung }}</option>
                                                  @endif
                                               @endforeach
                                            </select>
                                          </div>
                                        </div>
                                        
                                          <button type="reset" class="btn btn-default" data-dismiss="modal">Batal</button>
                                          <button type="submit" class="btn btn-primary">Simpan</button>
                                        
                                    </form>
                                  @endforeach
                </div>
              </div>

              </div>
            </div>
          </div>
                        <!-- end: content -->
@endsection
@section('javascript')
<!-- start: Javascript -->
  <script src="{{ asset('asset/js/jquery.min.js') }}"></script>
  <script src="{{ asset('asset/js/jquery.ui.min.js') }}"></script>
  <script src="{{ asset('asset/js/bootstrap.min.js') }}"></script>
<!-- plugins -->
  <script src="{{ asset('asset/js/plugins/moment.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.datatables.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/datatables.bootstrap.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.nicescroll.js') }}"></script>
<!-- custom -->
  <script src="{{ asset('asset/js/main.js') }}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('#datatables-example').DataTable();
  });
</script>
<!-- end: Javascript -->
@endsection

resources/views/kepegawaian/penilai-eksternal.blade.php
@extends('layouts.template')
@section('css')
  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/bootstrap.min.css')}}">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/datatables.bootstrap.min.css')}}"/>
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/font-awesome.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/animate.min.css')}}" />
  <link href="{{asset('asset/css/style.css')}}" rel="stylesheet">
  <!-- end: Css -->

  <!-- end: Css -->
  <!-- end: Css -->

  <link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">

@endsection

@section('profile')
  <li class="user-name"><span>{{auth::user()->username}}</span></li>
                    <li class="dropdown avatar-dropdown">
                     <img src="{{asset('asset/img/avatar.jpg')}}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                     <ul class="dropdown-menu user-dropdown">
                       <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
                       <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><span class="fa fa-power-off"></span> Logout</a></li>
                          {{-- Di panggil pada event onclick --}}
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>

                        </ul>
                      </li>
@endsection
@section('leftmenu')

@endsection
@section('content')
            <!-- tampilan data penilai eksternal -->
            <div id="content">
              <div class="tab-wrapper text-center">
                <div class="panel box-shadow-none text-left content-header">
                  <div class="panel-body" style="padding-bottom:0px">
                    <div class="col-md-12">
                      <h3 class="animated fadeInLeft"> Data Penilai Eksternal</h3>
                      <p class="animated fadeInDown">
                          Penilai  <span class="fa-angle-right fa"></span>  Penilai Eksternal
                              </p>
                    </div>

                  </div>
                  <div class="col-md-12 top-20 padding-0">
                    <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading"><h3>Penilai Eksternal </h3>
                            <a class="btn btn-round btn-danger" href="{{ url('tambah-penilai') }}">
                              <span class="fa fa-plus"></span> Tambah
                            </a>
                       </div>
                    <div class="panel-body">
                      <div class="responsive-table">
                        <!-- tabel penilai eksternal-->
                      <table id="tbeksternal" class="table table-striped table-bordered" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th style="width:4%; text-align: center;">No</th>
                          <th style="width:14%; text-align: center;">NIP</th>
                          <th style="width:11%; text-align: center;">NIDN</th>
                          <th style="width:16%; text-align: center;">Nama</th>
                          <th style="width:14%; text-align: center;">Universitas</th>
                          <th style="width:10%; text-align: center;">Rumpun</th>
                          <th style="width:10%; text-align: center;">Sub Rumpun</th>
                          <th style="width:10%; text-align: center;">Jabatan Fungsional</th>
                          <th style="width:10%; text-align: center;">Aksi</th>
                        </tr>
                      </thead>
                      <tbody>
                         @php $no = 1; @endphp
                         @foreach ( $eksternal as $data)
                              <tr id="{{$data->id_penilai_eks}}">
                                <td style="text-align: center;">{{ $no++ }}</td>
                                <td>{{ $data->nip }}</td>
                                <td>{{ $data->nidn }}</td>
                                <td>{{ $data->nama }}</td>
                                <td>{{ $data->universitas }}</td>
                                <td>{{ $data->rumpun }}</td>
                                <td>{{ $data->sub_rumpun }}</td>
                                <td>{{ $data->jabatan }}</td>
                                <td>
                                    <form class="form-group" action="{{ url('/hapus-penilai/'.$data->id_penilai_eks) }}" method="post">
                                      <a href="{{ url('/ubah-penilai/'.$data->id_penilai_eks) }}" class="btn-warning btn btn-circle btn-mn edit"><span class="fa fa-pencil" style="margin-top:7px;"></span></a>
                                      @csrf
                                      @method('delete')
                                      <button id="delete" class="btn btn-circle btn-mn btn-danger" value="{{ $data->id_penilai_eks }}" type="submit" onclick="return confirm('Yakin ingin menghapus data Penilai Eksternal {{ $data->nama }}?')"><span class="fa fa-trash"></span></button>
                                    </form>


                                </td>
                          </tr>
                          @endforeach
                        </tbody>

                        </table>

                      </div>

                  </div>

                  <!-- Modal -->





                  </div>


                </div>
              </div>

              </div>
            </div>
          </div>
                        <!-- end: content -->
@endsection
@section('javascript')
  <!-- start: Javascript -->
  <script src="{{asset('asset/js/jquery.min.js')}}"></script>
  <script src="{{asset('asset/js/jquery.ui.min.js')}}"></script>
  <script src="{{asset('asset/js/bootstrap.min.js')}}"></script>


  <!-- plugins -->
  <script src="{{asset('asset/js/plugins/moment.min.js')}}"></script>
  <script src="{{asset('asset/js/plugins/jquery.knob.js')}}"></script>
  <script src="{{asset('asset/js/plugins/ion.rangeSlider.min.js')}}"></script>
  <script src="{{asset('asset/js/plugins/bootstrap-material-datetimepicker.js')}}"></script>
  <script src="{{asset('asset/js/plugins/jquery.nicescroll.js')}}"></script>
  <script src="{{asset('asset/js/plugins/jquery.mask.min.js')}}"></script>
  <script src="{{asset('asset/js/plugins/select2.full.min.js')}}"></script>
  <script src="{{asset('asset/js/plugins/nouislider.min.js')}}"></script>
  <script src="{{asset('asset/js/plugins/jquery.validate.min.js')}}"></script>
  <!-- custom -->
  <script src="{{asset('asset/js/main.js')}}"></script>
  <!-- end: Javascript -->
  <!-- custom -->
   <script src="{{asset('asset/datejs/datepicker.en-US.js')}}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
  <script src="https://fengyuanchen.github.io/js/common.js"></script>
  <script src="{{asset('asset/date/js/main.js')}}"></script>
  <script src="{{asset('asset/date/js/datepicker.js')}}"></script>
  <script src="{{asset('asset/js/plugins/jquery.datatables.min.js') }}"></script>
  <script src="{{asset('asset/js/plugins/datatables.bootstrap.min.js') }}"></script>
  <!-- end: Javascript -->

<script type="text/javascript">
  $(document).ready(function(){
    $('#tbeksternal').DataTable();
  });
</script>
<!-- end: Javascript -->
@endsection

resources/views/kepegawaian/tambah-penilai.blade.php
@extends('layouts.template')
@section('css')
  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/bootstrap.min.css')}}">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/datatables.bootstrap.min.css')}}"/>
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/font-awesome.min.css')}}" />
  <link rel="stylesheet" type="text/css" href="{{asset('asset/css/plugins/animate.min.css')}}" />
  <link href="{{asset('asset/css/style.css')}}" rel="stylesheet">
  <!-- end: Css -->

  <!-- end: Css -->
  <!-- end: Css -->

  <link rel="shortcut icon" href="{{asset('asset/img/logomi.png')}}">

@endsection

@section('profile')
  <li class="user-name"><span>{{auth::user()->username}}</span></li>
                    <li class="dropdown avatar-dropdown">
                     <img src="{{asset('asset/img/avatar.jpg')}}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                     <ul class="dropdown-menu user-dropdown">
                       <li><a href="#"><span class="fa fa-user"></span> My Profile</a></li>
                       <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><span class="fa fa-power-off"></span> Logout</a></li>
                          {{-- Di panggil pada event onclick --}}
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>

                        </ul>
                      </li>
@endsection
@section('leftmenu')

@endsection
@section('content')
            <!-- Tambah penilai eksternal -->
            <div id="content">
              <div class="tab-wrapper text-center">
                <div class="panel box-shadow-none text-left content-header">
                  <div class="panel-body" style="padding-bottom:0px">
                    <div class="col-md-12">
                      <h3 class="animated fadeInLeft"> Data Penilai Eksternal</h3>
                      <p class="animated fadeInDown">
                          Penilai  <span class="fa-angle-right fa"></span>  Tambah Penilai Eksternal
                              </p>
                    </div>

                  </div>
                  <div class="col-md-12 top-20 padding-0">
                    <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading"><h3>Tambah Penilai Eksternal </h3>
                       </div>
                    <div class="panel-body">
                                      <form id="form" class="" action="{{ route('penilai-eksternal.store') }}" method="post">
                                      
                                        @csrf
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Nama</label>
                                         <div class="col-sm-8"><input type="text" class="form-control" id="nama" name="nama" required></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">NIP</label>
                                         <div class="col-sm-8"><input type="text" class="form-control" id="nip" name="nip" required></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">NIDN</label>
                                         <div class="col-sm-8"><input type="text" class="form-control" id="nidn" name="nidn" required></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Password</label>
                                         <div class="col-sm-8"><input type="password" class="form-control" id="password" name="password" required></div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Universitas</label>
                                          <div class="col-sm-8">
                                            <select class="form-control" id="universitas" name="universitas" required>
                                              @foreach($universitas as $univ)
                                              <option value="{{ $univ->nama_univ }}">{{ $univ->nama_univ}}</option>
                                              @endforeach
                                            </select>
                                          </div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px">
                                          <label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Rumpun</label>
                                          <div class="col-sm-8">
                                            <select class="form-control" id="rumpun" name="rumpun" required>
                                              @foreach($rumpun as $rump)
                                              <option value="{{ $rump->nama_rumpun}}">{{ $rump->nama_rumpun}}</option>
                                              @endforeach
                                            </select>
                                          </div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Sub Rumpun</label>
                                         <div class="col-sm-8">
                                            <select class="form-control" id="sub_rumpun" name="sub_rumpun" required>
                                              @foreach($sub_rumpun as $srump)
                                              <option value="{{ $srump->nama_rumpun_sub}}">{{ $srump->nama_rumpun_sub}}</option>
                                              @endforeach
                                            </select>
                                          </div>
                                        </div>
                                        <div class="form-group" style="padding-bottom:50px"><label class="col-sm-2 control-label text-right" style="padding-top: 6px; font-size: 16px;">Jabatan Fungsional</label>
                                          <div class="col-sm-8">
                                            <select class="form-control" id="jabatan" name="jabatan" required>
                                              @foreach($jabatan as $jab)
                                              <option value="{{ $jab->nama_jafung}}">{{ $jab->nama_jafung}}</option>
                                              @endforeach
                                            </select>

                                          </div>
                                        </div>
                                        
                                          <button type="reset" class="btn btn-default" data-dismiss="modal">Batal</button>
                                          <button type="submit" class="btn btn-primary">Simpan</button>
                                        
                                    </form>
                </div>
              </div>

              </div>
            </div>
          </div>
                        <!-- end: content -->
@endsection
@section('javascript')
<!-- start: Javascript -->
  <script src="{{ asset('asset/js/jquery.min.js') }}"></script>
  <script src="{{ asset('asset/js/jquery.ui.min.js') }}"></script>
  <script src="{{ asset('asset/js/bootstrap.min.js') }}"></script>
<!-- plugins -->
  <script src="{{ asset('asset/js/plugins/moment.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.datatables.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/datatables.bootstrap.min.js') }}"></script>
  <script src="{{ asset('asset/js/plugins/jquery.nicescroll.js') }}"></script>
<!-- custom -->
  <script src="{{ asset('asset/js/main.js') }}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('#datatables-example').DataTable();
  });
</script>
<!-- end: Javascript -->
@endsection